황경서 week5 hw
SNULION-12th/react-seminar pull request #32
Opened 2024-04-09 09:47 UTC by vonvon56

## 💎 과제 구현 설명
> _과제를 위해 사용했던 함수, 수정한 파일 등 구현 내용에 대한 간단한 설명을 작성해 주세요._
- 
## 🏁 PR 체크리스트
- [O] 코드가 오류 없이 정상적으로 실행되나요?
- [ ] 커밋 메시지 컨벤션(템플릿 활용)을 준수했나요?
- [O] 과제 마감기한을 준수했나요?

## 🖼️ Screenshot / Video
![image](https://github.com/SNULION-12th/react-seminar/assets/141728432/d2d1a24c-6bbb-4c01-88d3-da248f29725c)
![image](https://github.com/SNULION-12th/react-seminar/assets/141728432/b195cfa5-410d-41af-a9a4-39b76aa14247)

## 🙌 Issue
> _과제 수행 중 어려웠던 부분이나 궁금했던 점을 자유롭게 작성해 주세요._

2024-04-12 16:25 UTC, cheeze-hyeon requested changes
LGTM!! 그런데 지금 과제 PR 타겟팅이 `main` <- `gyeongseo-week5-hw` 로 되어있어요! `main` 말고 `gyeongseo-week5 `로 되도록 수정해주세요!

2024-04-12 16:25 UTC, cheeze-hyeon commented on src/component/Counter.js
> +export default Counter;
과제 PR에 훅 실습했던 내용의 파일이 들어있네요! 삭제해주세요~🙇‍♀️

2024-04-12 16:25 UTC, cheeze-hyeon commented on src/components/Comment/CommentElement.jsx
> +       Hint: 댓글의 내용을 저장하는 state와 수정 중인지 여부를 저장하는 state를 따로 만드는 게 좋겠죠? */
과제 내용이 반영이 안 된 것 같아요! 확인하시고 다시 커밋 남기고 푸쉬해주세요!!

2024-04-13 03:49 UTC, vonvon56 commented on src/components/Comment/CommentElement.jsx
> +       Hint: 댓글의 내용을 저장하는 state와 수정 중인지 여부를 저장하는 state를 따로 만드는 게 좋겠죠? */
헉 이것들 다 index.jsx에서 구현한 것 같습니다!! 
const [editingCommentId, setEditingCommentId] = useState(null); 나 newCommentContent 등으로 구현은 다 했는데 CommentElement.jsx에 있는 거랑 기능상 차이가 있나요?

2024-04-13 03:52 UTC, vonvon56 commented on src/component/Counter.js
> +export default Counter;
삭제해서 gyeongseo-week5-hw엔 반영됐는데 풀리퀘 새로 팔까요?!

2024-04-13 09:43 UTC, cheeze-hyeon commented on src/component/Counter.js
> +export default Counter;
아니요!! `gyeongseo-week5-hw` 브랜치에 반영되었다면 여기 PR에도 반영됩니다! file changed 탭 들어가서 보면 확인할 수 있어요😸

2024-04-13 09:50 UTC, cheeze-hyeon commented on src/components/Comment/CommentElement.jsx
> +       Hint: 댓글의 내용을 저장하는 state와 수정 중인지 여부를 저장하는 state를 따로 만드는 게 좋겠죠? */
과제에서 의도했던 바는 CommentElement를 댓글 하나에 해당하는 컴포넌트로 만들어서 재사용할 수 있게끔 하는 것이었어요! 지금 코드로도 잘 작동되는 거 확인하고 과제 제출했으니까 문제는 없겠지만 가능하면 컴포넌트를 분리해서 작성해주는 것이 더 깔끔하고 유지보수 측면에서 좋겠죠?? 컴포넌트의 분리와 관련해서 [4주차 노션](https://www.notion.so/4-React-791eca77111846d9b809da440f7ae22d?pvs=4#5e6455bb8e31407bac914ca4250125e4)에 내용이 있으니 한 번 읽어보는 것도 좋을 것 같습니다😊

2024-04-13 09:53 UTC, cheeze-hyeon commented on src/component/Counter.js
> +export default Counter;
![image](https://github.com/SNULION-12th/react-seminar/assets/103312340/7e112060-ccd3-465d-8d7c-b0296dfec007)
그리고 아래로 쭉 내려서 PR 확인해보면 커밋한 내용이 반영된 것도 확인할 수 있습니다~

2024-04-13 09:53 UTC, cheeze-hyeon approved these changes

2024-04-13 14:04 UTC, jsh6269 commented
LGTM! 코드 좋아요

2024-04-13 14:06 UTC, jsh6269 approved these changes
LGTM!! 좋은 코드입니당~

2024-04-14 13:01 UTC, merged