Roki week5 hw
SNULION-12th/react-seminar pull request #42
Opened 2024-04-11 09:51 UTC by rokiki2

## 💎 과제 구현 설명
> _과제를 위해 사용했던 함수, 수정한 파일 등 구현 내용에 대한 간단한 설명을 작성해 주세요._
- editcomment와 deletecomment 함수를 구현하였다. ID는 겹치지 않도록 따로 관리하였다.
## 🏁 PR 체크리스트
- [x] 코드가 오류 없이 정상적으로 실행되나요?
- [x] 커밋 메시지 컨벤션(템플릿 활용)을 준수했나요?
- [x] 과제 마감기한을 준수했나요?

## 🖼️ Screenshot / Video

## 🙌 Issue
> _과제 수행 중 어려웠던 부분이나 궁금했던 점을 자유롭게 작성해 주세요._

2024-04-11 15:45 UTC, Jack-Chagarr requested changes
쉽지 않은 과제였는데 고생하셨습니다! 작성한 내용 한번 읽어보시고 다시 한번 코드에 적용해서 확인해보세요~

2024-04-11 15:45 UTC, Jack-Chagarr commented on src/components/Comment/CommentElement.jsx
> +                        value={editContent.content}
editContent에는 content가 따로 없습니다! editContent 자체에 이미 comment의 content를 넣어주고 있네요~
그래서 지금은 수정하기를 눌러보면 수정해야 하는 댓글이 안나오고, 빈 라인이 나옵니다!

2024-04-11 15:45 UTC, Jack-Chagarr commented on src/components/Comment/CommentElement.jsx
> +    useEffect(() => { // add api call to check if user is the author of the comment
아래에 적은 코멘트를 적용해보면 예를 들어 네번째, 다섯번째 댓글을 추가하고, 두번째, 세번째 댓글을 삭제했을 때, 추가한 댓글의 수정 버튼을 눌러보면 이미 삭제한 댓글의 content가 나타나는 것을 볼 수 있습니다! 
이것은 comment가 바뀔 때마다 그 comment의 content로 setEditContent을 해주면 해결할 수 있을 것 같네요!
comment가 바뀔 때마다 변경을 해주기 위해서 우리는 useEffect라는 훅을 사용할 수 있겠죠?
```
    useEffect(() => { 
        setEditContent(comment.content)
    }, [comment]);
```

2024-04-11 15:45 UTC, Jack-Chagarr commented on src/components/Comment/index.jsx
> +    const [commentID, setCommentID] = useState(4);
4라는 숫자를 넣은 것은 지금 문제를 해결하는 데에는 충분하지만, 조금 더 일반적인 상황을 항상 고려하면서 코드를 짜는 습관을 들이면 좋을 것 같아요! 예를 들면 
```
const [commentID, setCommentID] = useState(comments.length);
```

2024-04-11 15:45 UTC, Jack-Chagarr commented on src/components/Comment/index.jsx
> +        const removeComment = commentList.filter((comment) => comment.id !== parseInt(commentId));
가급적이면 변수명은 보다 더 직관적으로, 다른 사람들이 이해할 수 있는 방식으로 적어주면 좋습니다!
removeComment라는 변수가 가지는 의미는 정확히 말하면 삭제되고 남은 댓글들을 의미합니다. 
CommentsAfterDeletion 처럼 복수의 의미와, "남은" 이라는 의미를 잘 담아 지으면 좋을 것 같아요!

2024-04-11 15:45 UTC, Jack-Chagarr commented on src/components/Comment/index.jsx
> +        console.log(commentId);
가능하면 과제 제출시에는 console.log나 print() 처럼 디버깅을 위해 작성한 코드는 지워주세요~

2024-04-12 14:59 UTC, Hypell reviewed
수고하셨습니다!!!

2024-04-27 05:03 UTC, merged