homework finish
SNULION-12th/react-seminar pull request #9
Opened 2024-04-02 10:03 UTC by jihochang03

## 💎 과제 구현 설명
> _과제를 위해 사용했던 함수, 수정한 파일 등 구현 내용에 대한 간단한 설명을 작성해 주세요._
- 
## 🏁 PR 체크리스트
- [ ] 코드가 오류 없이 정상적으로 실행되나요?
- [ ] 커밋 메시지 컨벤션(템플릿 활용)을 준수했나요?
- [ ] 과제 마감기한을 준수했나요?

## 🖼️ Screenshot / Video

## 🙌 Issue
> _과제 수행 중 어려웠던 부분이나 궁금했던 점을 자유롭게 작성해 주세요._

2024-04-02 10:08 UTC, sehyeon7 requested changes
다시하셈 별로임

2024-04-02 10:08 UTC, sehyeon7 commented on lionblog-hoyah/src/components/Header/index.jsx
> +      </Link>
ㅇㄴㅁㄹㅇㄴㄹㄴㅇㄹㄴ

2024-04-02 10:08 UTC, sehyeon7 commented on lionblog-hoyah/src/components/Header/index.jsx
> +        </Link>
22222

2024-04-02 10:08 UTC, sehyeon7 commented on lionblog-hoyah/src/components/Posts/index.jsx
> +        ))}
ㅁㅇㄴㄹㅇㄹㅇㄴㄹㅁㄴㅇ

2024-04-02 10:09 UTC, sehyeon7 commented on lionblog-hoyah/src/components/Posts/index.jsx
> +      <h1 className="font-extrabold text-2xl truncate">{post.title}</h1>
```suggestion
      <h2 className="font-extrabold text-2xl truncate">{post.title}</h2>
```

이렇게 바꿔

2024-04-02 10:18 UTC, sehyeon7 commented on lionblog-hoyah/src/routes/PostEditPage.jsx
> +  };
디테일 너무 좋아용 태그 삭제까지 구현!!

2024-04-02 10:24 UTC, sehyeon7 reviewed
구현 너무 잘 되어 있습니다! 디테일한 기능 구현까지!

2024-04-05 13:41 UTC, JINSEO0201 commented
PostEdit 페이지에서 태그 삭제하는거 저는 엄두가 안 나서 못했는데, 디테일하게 기능 구현을 정말 잘하신 것 같습니다

2024-04-12 12:22 UTC, merged